application: claseuninorte
version: 1
runtime: php55
api_version: 1

handlers:
- url: /loaderio-99a416f7464920eab3e8249b6ed59f4b.txt
  script: loaderio-99a416f7464920eab3e8249b6ed59f4b.txt
- url: /.*
  script: index.php
